# Generated by Django 5.0.1 on 2024-01-17 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='example.company')),
            ],
        ),
    ]
